name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8'

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update dependencies
        run: |
          pnpm update --latest
          pnpm audit --fix

      - name: Build and test
        run: |
          pnpm install
          pnpm run build
          pnpm run lint
          pnpm run type-check

      - name: Run security audit
        run: pnpm audit --prod

      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: '🔄 Automated dependency updates'
          body: |
            ## 🔄 Automated Dependency Updates
            
            This PR contains automated dependency updates.
            
            ### 📋 Changes Made
            - Updated all dependencies to their latest versions
            - Applied security fixes where available
            - All tests pass ✅
            
            ### 🔍 Review Checklist
            - [ ] Check for breaking changes in updated packages
            - [ ] Review security audit results
            - [ ] Test critical functionality
            - [ ] Check for any new TypeScript errors
            
            ### 🤖 Automated Checks
            - ✅ Build successful
            - ✅ Tests passing
            - ✅ No linting errors
            - ✅ TypeScript compilation successful
            - ✅ Security audit passed
            
            ---
            *This PR was created automatically by the dependency update workflow.*
          branch: chore/dependency-updates
          delete-branch: true

  security-audit:
    name: Weekly Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: |
          echo "## 🔒 Security Audit Report" > security-report.md
          echo "Generated on: $(date)" >> security-report.md
          echo "" >> security-report.md
          
          if pnpm audit --prod --json > audit-results.json 2>/dev/null; then
            echo "✅ No security vulnerabilities found" >> security-report.md
          else
            echo "⚠️ Security vulnerabilities detected:" >> security-report.md
            echo "" >> security-report.md
            echo '```json' >> security-report.md
            cat audit-results.json >> security-report.md
            echo '```' >> security-report.md
          fi

      - name: Create security issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let body = '## 🚨 Security Vulnerabilities Detected\n\n';
            
            try {
              const report = fs.readFileSync('security-report.md', 'utf8');
              body += report;
            } catch (error) {
              body += 'Error reading security report.';
            }
            
            body += '\n\n---\n*This issue was created automatically by the security audit workflow.*';
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Security Vulnerabilities Detected',
              body: body,
              labels: ['security', 'high-priority']
            });